name: Yaathri
description: A comprehensive travel data collection and trip planning Flutter app for NATPAC research.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^16.2.2
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Network & HTTP
  dio: ^5.3.2
  connectivity_plus: ^7.0.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Location Services
  geolocator: ^14.0.2
  location: ^8.0.1
  geocoding: ^4.0.0
  
  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1
  
  # Social Authentication
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^6.0.4
  
  # Image & Media
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  flutter_svg: ^2.0.9
  
  # Maps
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^3.1.0
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Background Services
  workmanager: ^0.9.0+3
  
  # File Handling
  path_provider: ^2.1.2
  file_picker: ^10.3.3
  
  # Date & Time
  intl: ^0.20.2
  
  # Charts & Analytics
  fl_chart: ^1.1.1
  
  # Animations
  lottie: ^3.3.2
  
  # Utils
  uuid: ^4.2.1
  crypto: ^3.0.3
  
  # Dependency Injection
  get_it: ^8.2.0
  
  # Cloud Storage
  cloudinary_public: ^0.23.1
  
  # Code Generation
  json_annotation: ^4.8.1
  retrofit: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
